FROM yarnpkg/node-yarn
RUN apt-get update -y && apt-get install nginx git wget supervisor -y
COPY go1.9.2.linux-amd64.tar.gz /
RUN tar xvf /go1.9.2.linux-amd64.tar.gz && mv /go /usr/local/
ENV GOPATH /go
ENV PATH /go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RUN go get github.com/AplaProject/go-apla
RUN mkdir /apla
RUN mkdir -p /s/s1
RUN cp $GOPATH/bin/go-apla /apla
RUN git clone https://github.com/AplaProject/apla-front.git
RUN git clone https://github.com/AplaProject/apla-tests.git /apla-tests
RUN apt-get -y install python3 \
    python3-pip
RUN pip3 install -r /apla-tests/requirements.txt
ADD  supervisord.d /etc/supervisord.d
COPY supervisor.conf /etc/
ADD  nginx/default /etc/nginx/sites-available/default
ADD  nginx/nginx.conf /etc/nginx/nginx.conf
RUN cd /apla-front && yarn install && yarn build
COPY settings.json /apla-front/build/
COPY start.sh /
COPY start2.sh /
COPY go_apla /
COPY fullnodes.sh /
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor.conf"]


