PRODUCT_BRAND_NAME="Genesis"
DB_HOST="genesis-db"
DB_NAME_PREFIX="genesis"
DB_USER="postgres"
DB_PASSWORD="genesis"
CENT_URL="http://genesis-cf:8000"

BLEX_REPO_URL="https://github.com/GenesisKernel/blockexplorer"
BLEX_BRANCH="develop"
BLEX_DB_NAME_PREFIX="genesis_blex_"
BLEX_DB_HOST="$DB_HOST"
BLEX_DB_PORT="$DB_PORT"
BLEX_DB_USER="$DB_USER"
BLEX_DB_PASSWORD="$DB_PASSWORD"
BLEX_REDIS_URL="redis://genesis-rq:6379/0"
